const { chromium } = require('C:/Users/Mr.xia/.workbuddy/binaries/node/versions/22.22.2-3/node_modules/@playwright/cli/node_modules/playwright-core')
const proxy = process.env.https_proxy
;(async () => {
  const b = await chromium.launch({ channel: 'msedge', proxy: proxy ? { server: proxy } : undefined })
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 } })
  const p = await ctx.newPage()
  await p.goto(process.argv[2], { waitUntil: 'load', timeout: 60000 })
  await p.waitForTimeout(7000)
  await p.fill('#task-input', '持久化测试任务')
  await p.click('#btn-add')
  await p.waitForTimeout(1500)
  const before = await p.$$eval('#today-list .task-item', (e) => e.map((x) => x.innerText.replace(/\s+/g, ' ')))
  console.log('加任务后:', JSON.stringify(before))
  await p.reload({ waitUntil: 'load' })
  await p.waitForTimeout(7000)
  const after = await p.$$eval('#today-list .task-item', (e) => e.map((x) => x.innerText.replace(/\s+/g, ' ')))
  console.log('刷新之后:', JSON.stringify(after))
  console.log(after.length === before.length && before.length > 0 ? 'PERSIST_OK' : 'PERSIST_FAIL')
  await b.close()
})().catch((e) => { console.error('FAILED', e.message); process.exit(1) })
